### ISSUE TITLE
Cant be used with self signed certs

### ISSUE THREAD

**Issue by kochd** [ratmole/MotionViewAndControll#1]
Hey there. This is probably a uncommon case:

I am using Apache to wrap TLS around Motions http server. This actually works fine but your application throws:
 <pre>javax.net.ssl.SSLPeerUnverifiedException: No peer certificate</pre>
Probably because my cert is self singed. A option to catch this would be nice.

Thank you very much for your work.

**Comment by ratmole** [comment]
Had the same issue as you and the only proper way is to provide a signed certificate, 
or to import your crt in your phone if it is rooted.

For more information on how to import the crt on your phone:

http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets

please try the latest apk (or build it your self) and let me know.
